### ISSUE TITLE
Kommentare und Meinungen

### ISSUE THREAD

**Issue by dempole** [dempole/Projekt-A#1]
Eure Kommentare und Meinungen sind hier herzlich Willkommen. 
Einfach auf diese Issue antworten!

**Comment by miczzz** [comment]
Ich hatte auch eine Art Idee für eine Art Quiz (wenn auch viel eingeschränkter nur bezogen aufs Lernen japanischer Silbenschrift). Die Idee mit dem personalisiertem Quiz finde ich echt gut!
